vich_uploader:
    db_driver: orm

    mappings:
        attachments_image:
            uri_prefix: /images/attachments
            upload_destination: '%kernel.project_dir%/public/images/attachments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
